// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: declare_property.proto

package envoy_source_extensions_common_wasm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WasmType int32

const (
	WasmType_Bytes       WasmType = 0
	WasmType_String      WasmType = 1
	WasmType_FlatBuffers WasmType = 2
	WasmType_Protobuf    WasmType = 3
)

// Enum value maps for WasmType.
var (
	WasmType_name = map[int32]string{
		0: "Bytes",
		1: "String",
		2: "FlatBuffers",
		3: "Protobuf",
	}
	WasmType_value = map[string]int32{
		"Bytes":       0,
		"String":      1,
		"FlatBuffers": 2,
		"Protobuf":    3,
	}
)

func (x WasmType) Enum() *WasmType {
	p := new(WasmType)
	*p = x
	return p
}

func (x WasmType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WasmType) Descriptor() protoreflect.EnumDescriptor {
	return file_declare_property_proto_enumTypes[0].Descriptor()
}

func (WasmType) Type() protoreflect.EnumType {
	return &file_declare_property_proto_enumTypes[0]
}

func (x WasmType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WasmType.Descriptor instead.
func (WasmType) EnumDescriptor() ([]byte, []int) {
	return file_declare_property_proto_rawDescGZIP(), []int{0}
}

type LifeSpan int32

const (
	LifeSpan_FilterChain          LifeSpan = 0
	LifeSpan_DownstreamRequest    LifeSpan = 1
	LifeSpan_DownstreamConnection LifeSpan = 2
)

// Enum value maps for LifeSpan.
var (
	LifeSpan_name = map[int32]string{
		0: "FilterChain",
		1: "DownstreamRequest",
		2: "DownstreamConnection",
	}
	LifeSpan_value = map[string]int32{
		"FilterChain":          0,
		"DownstreamRequest":    1,
		"DownstreamConnection": 2,
	}
)

func (x LifeSpan) Enum() *LifeSpan {
	p := new(LifeSpan)
	*p = x
	return p
}

func (x LifeSpan) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LifeSpan) Descriptor() protoreflect.EnumDescriptor {
	return file_declare_property_proto_enumTypes[1].Descriptor()
}

func (LifeSpan) Type() protoreflect.EnumType {
	return &file_declare_property_proto_enumTypes[1]
}

func (x LifeSpan) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LifeSpan.Descriptor instead.
func (LifeSpan) EnumDescriptor() ([]byte, []int) {
	return file_declare_property_proto_rawDescGZIP(), []int{1}
}

type DeclarePropertyArguments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Readonly bool     `protobuf:"varint,2,opt,name=readonly,proto3" json:"readonly,omitempty"`
	Type     WasmType `protobuf:"varint,3,opt,name=type,proto3,enum=envoy.source.extensions.common.wasm.WasmType" json:"type,omitempty"`
	Schema   []byte   `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"`
	Span     LifeSpan `protobuf:"varint,5,opt,name=span,proto3,enum=envoy.source.extensions.common.wasm.LifeSpan" json:"span,omitempty"`
}

func (x *DeclarePropertyArguments) Reset() {
	*x = DeclarePropertyArguments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_declare_property_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeclarePropertyArguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclarePropertyArguments) ProtoMessage() {}

func (x *DeclarePropertyArguments) ProtoReflect() protoreflect.Message {
	mi := &file_declare_property_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclarePropertyArguments.ProtoReflect.Descriptor instead.
func (*DeclarePropertyArguments) Descriptor() ([]byte, []int) {
	return file_declare_property_proto_rawDescGZIP(), []int{0}
}

func (x *DeclarePropertyArguments) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeclarePropertyArguments) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

func (x *DeclarePropertyArguments) GetType() WasmType {
	if x != nil {
		return x.Type
	}
	return WasmType_Bytes
}

func (x *DeclarePropertyArguments) GetSchema() []byte {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *DeclarePropertyArguments) GetSpan() LifeSpan {
	if x != nil {
		return x.Span
	}
	return LifeSpan_FilterChain
}

type InjectEncodedDataToFilterChainArguments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body      string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Endstream bool   `protobuf:"varint,2,opt,name=endstream,proto3" json:"endstream,omitempty"`
}

func (x *InjectEncodedDataToFilterChainArguments) Reset() {
	*x = InjectEncodedDataToFilterChainArguments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_declare_property_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InjectEncodedDataToFilterChainArguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectEncodedDataToFilterChainArguments) ProtoMessage() {}

func (x *InjectEncodedDataToFilterChainArguments) ProtoReflect() protoreflect.Message {
	mi := &file_declare_property_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectEncodedDataToFilterChainArguments.ProtoReflect.Descriptor instead.
func (*InjectEncodedDataToFilterChainArguments) Descriptor() ([]byte, []int) {
	return file_declare_property_proto_rawDescGZIP(), []int{1}
}

func (x *InjectEncodedDataToFilterChainArguments) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *InjectEncodedDataToFilterChainArguments) GetEndstream() bool {
	if x != nil {
		return x.Endstream
	}
	return false
}

var File_declare_property_proto protoreflect.FileDescriptor

var file_declare_property_proto_rawDesc = []byte{
	0x0a, 0x16, 0x64, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x23, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2e,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x22, 0xe8, 0x01,
	0x0a, 0x18, 0x44, 0x65, 0x63, 0x6c, 0x61, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x79, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x65, 0x61, 0x64, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x72, 0x65, 0x61, 0x64, 0x6f, 0x6e, 0x6c, 0x79, 0x12, 0x41, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x65, 0x6e, 0x76, 0x6f, 0x79,
	0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x57,
	0x61, 0x73, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x41, 0x0a, 0x04, 0x73, 0x70, 0x61, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2e, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x77, 0x61, 0x73, 0x6d, 0x2e, 0x4c, 0x69, 0x66, 0x65, 0x53, 0x70,
	0x61, 0x6e, 0x52, 0x04, 0x73, 0x70, 0x61, 0x6e, 0x22, 0x5b, 0x0a, 0x27, 0x49, 0x6e, 0x6a, 0x65,
	0x63, 0x74, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x54, 0x6f, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x2a, 0x40, 0x0a, 0x08, 0x57, 0x61, 0x73, 0x6d, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x79, 0x74, 0x65, 0x73, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x46, 0x6c, 0x61, 0x74,
	0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x73, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x10, 0x03, 0x2a, 0x4c, 0x0a, 0x08, 0x4c, 0x69, 0x66, 0x65, 0x53,
	0x70, 0x61, 0x6e, 0x12, 0x0f, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x44, 0x6f, 0x77, 0x6e, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x44,
	0x6f, 0x77, 0x6e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x10, 0x02, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_declare_property_proto_rawDescOnce sync.Once
	file_declare_property_proto_rawDescData = file_declare_property_proto_rawDesc
)

func file_declare_property_proto_rawDescGZIP() []byte {
	file_declare_property_proto_rawDescOnce.Do(func() {
		file_declare_property_proto_rawDescData = protoimpl.X.CompressGZIP(file_declare_property_proto_rawDescData)
	})
	return file_declare_property_proto_rawDescData
}

var file_declare_property_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_declare_property_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_declare_property_proto_goTypes = []interface{}{
	(WasmType)(0),                    // 0: envoy.source.extensions.common.wasm.WasmType
	(LifeSpan)(0),                    // 1: envoy.source.extensions.common.wasm.LifeSpan
	(*DeclarePropertyArguments)(nil), // 2: envoy.source.extensions.common.wasm.DeclarePropertyArguments
	(*InjectEncodedDataToFilterChainArguments)(nil), // 3: envoy.source.extensions.common.wasm.InjectEncodedDataToFilterChainArguments
}
var file_declare_property_proto_depIdxs = []int32{
	0, // 0: envoy.source.extensions.common.wasm.DeclarePropertyArguments.type:type_name -> envoy.source.extensions.common.wasm.WasmType
	1, // 1: envoy.source.extensions.common.wasm.DeclarePropertyArguments.span:type_name -> envoy.source.extensions.common.wasm.LifeSpan
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_declare_property_proto_init() }
func file_declare_property_proto_init() {
	if File_declare_property_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_declare_property_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeclarePropertyArguments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_declare_property_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InjectEncodedDataToFilterChainArguments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_declare_property_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_declare_property_proto_goTypes,
		DependencyIndexes: file_declare_property_proto_depIdxs,
		EnumInfos:         file_declare_property_proto_enumTypes,
		MessageInfos:      file_declare_property_proto_msgTypes,
	}.Build()
	File_declare_property_proto = out.File
	file_declare_property_proto_rawDesc = nil
	file_declare_property_proto_goTypes = nil
	file_declare_property_proto_depIdxs = nil
}
