profile: k8s
global:
  install: k8s # install mode k8s/local-k8s/local-docker/local
  ingressClass: higress
  enableIstioAPI: false
  enableGatewayAPI: false
  namespace: higress-system

console:
  replicas: 1
  o11yEnabled: false

gateway:
  replicas: 2

controller:
  replicas: 1

# values passed through to helm
values:

charts:
  higress:
    url: https://higress.io/helm-charts
    name: higress
    version: latest
  standalone:
    url: https://higress.io/standalone/get-higress.sh
    name: standalone
    version: latest
