codecov:
  require_ci_to_pass: yes
coverage:
  status:
    patch: 
      default:
        target: 50%
        threshold: 0%
        if_ci_failed: error # success, failure, error, ignore
    project:
      default:
        target: auto
        threshold: 1%
        if_not_found: success
    changes: no
  precision: 2
  round: down
  range: 50..100
ignore:
  - "helm/**"
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no