// Copyright (c) 2022 Alibaba Group Holding Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/alibaba/higress/client/pkg/apis/networking/v1"
	scheme "github.com/alibaba/higress/client/pkg/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// McpBridgesGetter has a method to return a McpBridgeInterface.
// A group's client should implement this interface.
type McpBridgesGetter interface {
	McpBridges(namespace string) McpBridgeInterface
}

// McpBridgeInterface has methods to work with McpBridge resources.
type McpBridgeInterface interface {
	Create(ctx context.Context, mcpBridge *v1.McpBridge, opts metav1.CreateOptions) (*v1.McpBridge, error)
	Update(ctx context.Context, mcpBridge *v1.McpBridge, opts metav1.UpdateOptions) (*v1.McpBridge, error)
	UpdateStatus(ctx context.Context, mcpBridge *v1.McpBridge, opts metav1.UpdateOptions) (*v1.McpBridge, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.McpBridge, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.McpBridgeList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.McpBridge, err error)
	McpBridgeExpansion
}

// mcpBridges implements McpBridgeInterface
type mcpBridges struct {
	client rest.Interface
	ns     string
}

// newMcpBridges returns a McpBridges
func newMcpBridges(c *NetworkingV1Client, namespace string) *mcpBridges {
	return &mcpBridges{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the mcpBridge, and returns the corresponding mcpBridge object, and an error if there is any.
func (c *mcpBridges) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.McpBridge, err error) {
	result = &v1.McpBridge{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mcpbridges").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of McpBridges that match those selectors.
func (c *mcpBridges) List(ctx context.Context, opts metav1.ListOptions) (result *v1.McpBridgeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.McpBridgeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mcpbridges").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested mcpBridges.
func (c *mcpBridges) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("mcpbridges").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a mcpBridge and creates it.  Returns the server's representation of the mcpBridge, and an error, if there is any.
func (c *mcpBridges) Create(ctx context.Context, mcpBridge *v1.McpBridge, opts metav1.CreateOptions) (result *v1.McpBridge, err error) {
	result = &v1.McpBridge{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("mcpbridges").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mcpBridge).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a mcpBridge and updates it. Returns the server's representation of the mcpBridge, and an error, if there is any.
func (c *mcpBridges) Update(ctx context.Context, mcpBridge *v1.McpBridge, opts metav1.UpdateOptions) (result *v1.McpBridge, err error) {
	result = &v1.McpBridge{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mcpbridges").
		Name(mcpBridge.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mcpBridge).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *mcpBridges) UpdateStatus(ctx context.Context, mcpBridge *v1.McpBridge, opts metav1.UpdateOptions) (result *v1.McpBridge, err error) {
	result = &v1.McpBridge{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mcpbridges").
		Name(mcpBridge.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mcpBridge).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the mcpBridge and deletes it. Returns an error if one occurs.
func (c *mcpBridges) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mcpbridges").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *mcpBridges) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mcpbridges").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched mcpBridge.
func (c *mcpBridges) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.McpBridge, err error) {
	result = &v1.McpBridge{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("mcpbridges").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
