apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ include "gateway.name" . }}-global-custom-response
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway.labels" . | nindent 4}}
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.cors
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.custom_response
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.custom_response.v3.CustomResponse