{{- if and .Values.global.ingressClass (ne (lower .Values.global.ingressClass) "nginx") }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.global.ingressClass }}
spec:
  controller: higress.io/higress-controller
{{- end }}
