blank_issues_enabled: true
contact_links:
  - name: Ask a question 💬
    url: https://github.com/alibaba/higress/discussions
    about: Ask a question or request support for using Higress.
  - name: Report a security vulnerability 🔒
    url: https://github.com/alibaba/higress/blob/main/SECURITY.md
    about: Please review our security policy for more details
