apiVersion: v2
appVersion: 0.5.3
description: Helm chart for deploying higress gateways
icon: https://higress.io/img/higress_logo_small.png
keywords:
- higress
- gateways
name: higress-local
sources:
- http://github.com/alibaba/higress
dependencies:
- name: higress
  repository: "file://../../higress"
  version: 0.5.3
type: application
version: 0.5.3
