kind: Pod
apiVersion: v1
metadata:
  name: upstream-example
  labels:
    app: upstream-example
spec:
  containers:
    - name: upstream-example
      image: registry.cn-hangzhou.aliyuncs.com/dspo/upstream_example:2022-11-23-162000
---
kind: Service
apiVersion: v1
metadata:
  name: upstream-example
spec:
  selector:
    app: upstream-example
  ports:
    - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: upstream-example
  annotations:
    "nginx.ingress.kubernetes.io/rewrite-target": /$2
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /upstream-example(/|$)(.+)
            backend:
              service:
                name: upstream-example
                port:
                  number: 8080
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: upstream-example
#spec:
#  rules:
#    - http:
#        paths:
#          - pathType: Prefix
#            path: /upstream-example/redirect5
#            backend:
#              service:
#                name: upstream-example
#                port:
#                  number: 8080
---
kind: Pod
apiVersion: v1
metadata:
  name: foo-app
  labels:
    app: foo
spec:
  containers:
  - name: foo-app
    image: higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/http-echo:0.2.3
    args:
    - "-text=foo"
---
kind: Service
apiVersion: v1
metadata:
  name: foo-service
spec:
  selector:
    app: foo
  ports:
  # Default port used by the image
  - port: 5678
---
kind: Pod
apiVersion: v1
metadata:
  name: bar-app
  labels:
    app: bar
spec:
  containers:
  - name: bar-app
    image: higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/http-echo:0.2.3
    args:
    - "-text=bar"
---
kind: Service
apiVersion: v1
metadata:
  name: bar-service
spec:
  selector:
    app: bar
  ports:
  # Default port used by the image
  - port: 5678
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foo
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/foo"
        backend:
          service:
            name: foo-service
            port:
              number: 5678
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bar
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/bar"
        backend:
          service:
            name: bar-service
            port:
              number: 5678
---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: proxy-redirect-example
  namespace: higress-system
spec:
  selector:
    matchLabels:
      higress: higress-system-higress-gateway
  pluginConfig:
    "http_status_code":
      - 201
      - 301
      - 302
      - 303
      - 307
      - 308
    "proxy_redirect":
      - 'http://web1:8080 http://localhost/web1'
      - '~*/user/([^/]+)/(.+)$ http://$1.example.com/$2'
      - 'default'
  url: oci://registry.cn-hangzhou.aliyuncs.com/dspo/proxy-redirect:20221124-100639