profile: k8s
global:
  install: k8s # install mode k8s/local-k8s/local-docker/local
  ingressClass: higress
  enableIstioAPI: false
  enableGatewayAPI: false
  namespace: higress-system

console:
  replicas: 1
  o11yEnabled: false
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 2048Mi

gateway:
  replicas: 2
  resources:
    requests:
      cpu: 2000m
      memory: 2048Mi
    limits:
      cpu: 2000m
      memory: 2048Mi

controller:
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 2048Mi
    limits:
      cpu: 1000m
      memory: 2048Mi

# values passed through to helm
values:

charts:
  higress:
    url: https://higress.io/helm-charts
    name: higress
    version: latest
  standalone:
    url: https://higress.io/standalone/get-higress.sh
    name: standalone
    version: latest
