// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: networking/v1/http_2_rpc.proto

package v1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	_ "istio.io/gogo-genproto/googleapis/google/api"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// <!-- crd generation tags
// +cue-gen:Http2Rpc:groupName:networking.higress.io
// +cue-gen:Http2Rpc:version:v1
// +cue-gen:Http2Rpc:storageVersion
// +cue-gen:Http2Rpc:annotations:helm.sh/resource-policy=keep
// +cue-gen:Http2Rpc:subresource:status
// +cue-gen:Http2Rpc:scope:Namespaced
// +cue-gen:Http2Rpc:resource:categories=higress-io,plural=Http2Rpcs
// +cue-gen:Http2Rpc:preserveUnknownFields:false
// -->
//
// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=networking.higress.io/v1
// +genclient
// +k8s:deepcopy-gen=true
// -->
type Http2Rpc struct {
	RouteType            string    `protobuf:"bytes,1,opt,name=routeType,proto3" json:"routeType,omitempty"`
	RouteService         string    `protobuf:"bytes,2,opt,name=routeService,proto3" json:"routeService,omitempty"`
	Methods              []*Method `protobuf:"bytes,3,rep,name=methods,proto3" json:"methods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Http2Rpc) Reset()         { *m = Http2Rpc{} }
func (m *Http2Rpc) String() string { return proto.CompactTextString(m) }
func (*Http2Rpc) ProtoMessage()    {}
func (*Http2Rpc) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc706c3b890c1c84, []int{0}
}
func (m *Http2Rpc) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Http2Rpc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Http2Rpc.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Http2Rpc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Http2Rpc.Merge(m, src)
}
func (m *Http2Rpc) XXX_Size() int {
	return m.Size()
}
func (m *Http2Rpc) XXX_DiscardUnknown() {
	xxx_messageInfo_Http2Rpc.DiscardUnknown(m)
}

var xxx_messageInfo_Http2Rpc proto.InternalMessageInfo

func (m *Http2Rpc) GetRouteType() string {
	if m != nil {
		return m.RouteType
	}
	return ""
}

func (m *Http2Rpc) GetRouteService() string {
	if m != nil {
		return m.RouteService
	}
	return ""
}

func (m *Http2Rpc) GetMethods() []*Method {
	if m != nil {
		return m.Methods
	}
	return nil
}

type Method struct {
	ServiceMethod        string   `protobuf:"bytes,1,opt,name=serviceMethod,proto3" json:"serviceMethod,omitempty"`
	HttpPath             string   `protobuf:"bytes,2,opt,name=httpPath,proto3" json:"httpPath,omitempty"`
	HttpMethods          []string `protobuf:"bytes,3,rep,name=httpMethods,proto3" json:"httpMethods,omitempty"`
	HeadersAttach        string   `protobuf:"bytes,4,opt,name=headersAttach,proto3" json:"headersAttach,omitempty"`
	Params               []*Param `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Method) Reset()         { *m = Method{} }
func (m *Method) String() string { return proto.CompactTextString(m) }
func (*Method) ProtoMessage()    {}
func (*Method) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc706c3b890c1c84, []int{1}
}
func (m *Method) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Method) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Method.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Method) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method.Merge(m, src)
}
func (m *Method) XXX_Size() int {
	return m.Size()
}
func (m *Method) XXX_DiscardUnknown() {
	xxx_messageInfo_Method.DiscardUnknown(m)
}

var xxx_messageInfo_Method proto.InternalMessageInfo

func (m *Method) GetServiceMethod() string {
	if m != nil {
		return m.ServiceMethod
	}
	return ""
}

func (m *Method) GetHttpPath() string {
	if m != nil {
		return m.HttpPath
	}
	return ""
}

func (m *Method) GetHttpMethods() []string {
	if m != nil {
		return m.HttpMethods
	}
	return nil
}

func (m *Method) GetHeadersAttach() string {
	if m != nil {
		return m.HeadersAttach
	}
	return ""
}

func (m *Method) GetParams() []*Param {
	if m != nil {
		return m.Params
	}
	return nil
}

type Param struct {
	ParamSource          string   `protobuf:"bytes,1,opt,name=paramSource,proto3" json:"paramSource,omitempty"`
	ParamKey             string   `protobuf:"bytes,2,opt,name=paramKey,proto3" json:"paramKey,omitempty"`
	ParamType            string   `protobuf:"bytes,3,opt,name=paramType,proto3" json:"paramType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Param) Reset()         { *m = Param{} }
func (m *Param) String() string { return proto.CompactTextString(m) }
func (*Param) ProtoMessage()    {}
func (*Param) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc706c3b890c1c84, []int{2}
}
func (m *Param) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Param) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Param.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Param) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Param.Merge(m, src)
}
func (m *Param) XXX_Size() int {
	return m.Size()
}
func (m *Param) XXX_DiscardUnknown() {
	xxx_messageInfo_Param.DiscardUnknown(m)
}

var xxx_messageInfo_Param proto.InternalMessageInfo

func (m *Param) GetParamSource() string {
	if m != nil {
		return m.ParamSource
	}
	return ""
}

func (m *Param) GetParamKey() string {
	if m != nil {
		return m.ParamKey
	}
	return ""
}

func (m *Param) GetParamType() string {
	if m != nil {
		return m.ParamType
	}
	return ""
}

func init() {
	proto.RegisterType((*Http2Rpc)(nil), "higress.networking.v1.Http2Rpc")
	proto.RegisterType((*Method)(nil), "higress.networking.v1.Method")
	proto.RegisterType((*Param)(nil), "higress.networking.v1.Param")
}

func init() { proto.RegisterFile("networking/v1/http_2_rpc.proto", fileDescriptor_dc706c3b890c1c84) }

var fileDescriptor_dc706c3b890c1c84 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcf, 0x4a, 0x2b, 0x31,
	0x14, 0xc6, 0x49, 0xff, 0xdd, 0x36, 0xbd, 0xdd, 0x04, 0x2e, 0x0c, 0x17, 0x1d, 0xcb, 0x20, 0x52,
	0x44, 0x66, 0x68, 0x75, 0x25, 0xb8, 0x68, 0x57, 0x82, 0x14, 0xca, 0xd4, 0x95, 0x9b, 0x92, 0x99,
	0xc6, 0x49, 0xb0, 0x6d, 0x42, 0x26, 0x33, 0xd2, 0x27, 0xf1, 0x95, 0x5c, 0xba, 0x76, 0x25, 0xf3,
	0x24, 0x92, 0x4c, 0xff, 0x4c, 0x40, 0x77, 0xc9, 0xef, 0xfb, 0x72, 0xf8, 0x4e, 0xce, 0x81, 0xee,
	0x86, 0xa8, 0x57, 0x2e, 0x5f, 0xd8, 0x26, 0x09, 0xf2, 0x61, 0x40, 0x95, 0x12, 0x8b, 0xd1, 0x42,
	0x8a, 0xd8, 0x17, 0x92, 0x2b, 0x8e, 0xfe, 0x51, 0x96, 0x48, 0x92, 0xa6, 0xfe, 0xd1, 0xe7, 0xe7,
	0xc3, 0xff, 0x67, 0x09, 0xe7, 0xc9, 0x8a, 0x04, 0x58, 0xb0, 0xe0, 0x99, 0x91, 0xd5, 0x72, 0x11,
	0x11, 0x8a, 0x73, 0xc6, 0x65, 0xf9, 0xce, 0x7b, 0x03, 0xb0, 0x7d, 0xaf, 0x94, 0x18, 0x85, 0x22,
	0x46, 0x1e, 0xec, 0x48, 0x9e, 0x29, 0xf2, 0xb8, 0x15, 0xc4, 0x01, 0x7d, 0x30, 0xe8, 0x4c, 0x1a,
	0xc5, 0x18, 0xd4, 0xc2, 0x23, 0x46, 0x03, 0xf8, 0xd7, 0x5c, 0xe6, 0x44, 0xe6, 0x2c, 0x26, 0x4e,
	0xad, 0x62, 0xb3, 0x14, 0x74, 0x07, 0xff, 0xac, 0x89, 0xa2, 0x7c, 0x99, 0x3a, 0xf5, 0x7e, 0x7d,
	0xd0, 0x1d, 0x9d, 0xfa, 0x3f, 0x86, 0xf4, 0xa7, 0xc6, 0xb5, 0xab, 0xb1, 0x7f, 0xe3, 0x7d, 0x02,
	0xd8, 0x2a, 0x15, 0x74, 0x09, 0x7b, 0x69, 0x59, 0xb4, 0x04, 0x56, 0x36, 0x5b, 0x42, 0x7d, 0xd8,
	0xd6, 0x9f, 0x33, 0xc3, 0x8a, 0x5a, 0xd9, 0x0e, 0x14, 0x5d, 0xc0, 0xae, 0x3e, 0x4f, 0x2b, 0xd9,
	0xf6, 0xa6, 0xaa, 0x80, 0xce, 0x61, 0x8f, 0x12, 0xbc, 0x24, 0x32, 0x1d, 0x2b, 0x85, 0x63, 0xea,
	0x34, 0x74, 0xb9, 0xd0, 0x86, 0xe8, 0x06, 0xb6, 0x04, 0x96, 0x78, 0x9d, 0x3a, 0x4d, 0xd3, 0xe4,
	0xc9, 0x2f, 0x4d, 0xce, 0xb4, 0x29, 0xdc, 0x79, 0xbd, 0x0c, 0x36, 0x0d, 0xd0, 0x61, 0x0c, 0x9a,
	0xf3, 0x4c, 0xc6, 0xf6, 0xa7, 0x57, 0x05, 0xdd, 0x96, 0xb9, 0x3e, 0x90, 0xad, 0xdd, 0xd6, 0x9e,
	0xea, 0xe1, 0x99, 0xb3, 0x19, 0x5e, 0xbd, 0x3a, 0xbc, 0x03, 0x9e, 0xdc, 0xbe, 0x17, 0x2e, 0xf8,
	0x28, 0x5c, 0xf0, 0x55, 0xb8, 0xe0, 0xe9, 0x2a, 0x61, 0x8a, 0x66, 0x91, 0x1f, 0xf3, 0x75, 0x80,
	0x57, 0x2c, 0xc2, 0x11, 0x0e, 0x76, 0xe1, 0xcd, 0xc2, 0x58, 0x2b, 0x17, 0xb5, 0xcc, 0xc2, 0x5c,
	0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xcf, 0xa0, 0xbc, 0x66, 0x8a, 0x02, 0x00, 0x00,
}

func (m *Http2Rpc) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Http2Rpc) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Http2Rpc) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Methods) > 0 {
		for iNdEx := len(m.Methods) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Methods[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintHttp_2Rpc(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.RouteService) > 0 {
		i -= len(m.RouteService)
		copy(dAtA[i:], m.RouteService)
		i = encodeVarintHttp_2Rpc(dAtA, i, uint64(len(m.RouteService)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.RouteType) > 0 {
		i -= len(m.RouteType)
		copy(dAtA[i:], m.RouteType)
		i = encodeVarintHttp_2Rpc(dAtA, i, uint64(len(m.RouteType)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Method) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Method) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Method) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Params) > 0 {
		for iNdEx := len(m.Params) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Params[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintHttp_2Rpc(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.HeadersAttach) > 0 {
		i -= len(m.HeadersAttach)
		copy(dAtA[i:], m.HeadersAttach)
		i = encodeVarintHttp_2Rpc(dAtA, i, uint64(len(m.HeadersAttach)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.HttpMethods) > 0 {
		for iNdEx := len(m.HttpMethods) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.HttpMethods[iNdEx])
			copy(dAtA[i:], m.HttpMethods[iNdEx])
			i = encodeVarintHttp_2Rpc(dAtA, i, uint64(len(m.HttpMethods[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.HttpPath) > 0 {
		i -= len(m.HttpPath)
		copy(dAtA[i:], m.HttpPath)
		i = encodeVarintHttp_2Rpc(dAtA, i, uint64(len(m.HttpPath)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ServiceMethod) > 0 {
		i -= len(m.ServiceMethod)
		copy(dAtA[i:], m.ServiceMethod)
		i = encodeVarintHttp_2Rpc(dAtA, i, uint64(len(m.ServiceMethod)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Param) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Param) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Param) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.ParamType) > 0 {
		i -= len(m.ParamType)
		copy(dAtA[i:], m.ParamType)
		i = encodeVarintHttp_2Rpc(dAtA, i, uint64(len(m.ParamType)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ParamKey) > 0 {
		i -= len(m.ParamKey)
		copy(dAtA[i:], m.ParamKey)
		i = encodeVarintHttp_2Rpc(dAtA, i, uint64(len(m.ParamKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ParamSource) > 0 {
		i -= len(m.ParamSource)
		copy(dAtA[i:], m.ParamSource)
		i = encodeVarintHttp_2Rpc(dAtA, i, uint64(len(m.ParamSource)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintHttp_2Rpc(dAtA []byte, offset int, v uint64) int {
	offset -= sovHttp_2Rpc(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Http2Rpc) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RouteType)
	if l > 0 {
		n += 1 + l + sovHttp_2Rpc(uint64(l))
	}
	l = len(m.RouteService)
	if l > 0 {
		n += 1 + l + sovHttp_2Rpc(uint64(l))
	}
	if len(m.Methods) > 0 {
		for _, e := range m.Methods {
			l = e.Size()
			n += 1 + l + sovHttp_2Rpc(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Method) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ServiceMethod)
	if l > 0 {
		n += 1 + l + sovHttp_2Rpc(uint64(l))
	}
	l = len(m.HttpPath)
	if l > 0 {
		n += 1 + l + sovHttp_2Rpc(uint64(l))
	}
	if len(m.HttpMethods) > 0 {
		for _, s := range m.HttpMethods {
			l = len(s)
			n += 1 + l + sovHttp_2Rpc(uint64(l))
		}
	}
	l = len(m.HeadersAttach)
	if l > 0 {
		n += 1 + l + sovHttp_2Rpc(uint64(l))
	}
	if len(m.Params) > 0 {
		for _, e := range m.Params {
			l = e.Size()
			n += 1 + l + sovHttp_2Rpc(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Param) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ParamSource)
	if l > 0 {
		n += 1 + l + sovHttp_2Rpc(uint64(l))
	}
	l = len(m.ParamKey)
	if l > 0 {
		n += 1 + l + sovHttp_2Rpc(uint64(l))
	}
	l = len(m.ParamType)
	if l > 0 {
		n += 1 + l + sovHttp_2Rpc(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovHttp_2Rpc(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozHttp_2Rpc(x uint64) (n int) {
	return sovHttp_2Rpc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Http2Rpc) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHttp_2Rpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Http2Rpc: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Http2Rpc: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RouteType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttp_2Rpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RouteType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RouteService", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttp_2Rpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RouteService = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Methods", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttp_2Rpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Methods = append(m.Methods, &Method{})
			if err := m.Methods[len(m.Methods)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHttp_2Rpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Method) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHttp_2Rpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Method: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Method: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceMethod", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttp_2Rpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceMethod = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HttpPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttp_2Rpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HttpPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HttpMethods", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttp_2Rpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HttpMethods = append(m.HttpMethods, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeadersAttach", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttp_2Rpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HeadersAttach = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttp_2Rpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Params = append(m.Params, &Param{})
			if err := m.Params[len(m.Params)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHttp_2Rpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Param) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHttp_2Rpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Param: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Param: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParamSource", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttp_2Rpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParamSource = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParamKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttp_2Rpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParamKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParamType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHttp_2Rpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParamType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHttp_2Rpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHttp_2Rpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipHttp_2Rpc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowHttp_2Rpc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHttp_2Rpc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHttp_2Rpc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthHttp_2Rpc
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupHttp_2Rpc
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthHttp_2Rpc
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthHttp_2Rpc        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHttp_2Rpc          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHttp_2Rpc = fmt.Errorf("proto: unexpected end of group")
)
