// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: networking/v1/mcp_bridge.proto

package v1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	_ "istio.io/gogo-genproto/googleapis/google/api"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// <!-- crd generation tags
// +cue-gen:McpBridge:groupName:networking.higress.io
// +cue-gen:McpBridge:version:v1
// +cue-gen:McpBridge:storageVersion
// +cue-gen:McpBridge:annotations:helm.sh/resource-policy=keep
// +cue-gen:McpBridge:subresource:status
// +cue-gen:McpBridge:scope:Namespaced
// +cue-gen:McpBridge:resource:categories=higress-io,plural=mcpbridges
// +cue-gen:McpBridge:preserveUnknownFields:false
// -->
//
// <!-- go code generation tags
// +kubetype-gen
// +kubetype-gen:groupVersion=networking.higress.io/v1
// +genclient
// +k8s:deepcopy-gen=true
// -->
type McpBridge struct {
	Registries           []*RegistryConfig `protobuf:"bytes,1,rep,name=registries,proto3" json:"registries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *McpBridge) Reset()         { *m = McpBridge{} }
func (m *McpBridge) String() string { return proto.CompactTextString(m) }
func (*McpBridge) ProtoMessage()    {}
func (*McpBridge) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fcc59a15c34642d, []int{0}
}
func (m *McpBridge) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *McpBridge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_McpBridge.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *McpBridge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_McpBridge.Merge(m, src)
}
func (m *McpBridge) XXX_Size() int {
	return m.Size()
}
func (m *McpBridge) XXX_DiscardUnknown() {
	xxx_messageInfo_McpBridge.DiscardUnknown(m)
}

var xxx_messageInfo_McpBridge proto.InternalMessageInfo

func (m *McpBridge) GetRegistries() []*RegistryConfig {
	if m != nil {
		return m.Registries
	}
	return nil
}

type RegistryConfig struct {
	Type                  string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name                  string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Domain                string   `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Port                  uint32   `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	NacosAddressServer    string   `protobuf:"bytes,5,opt,name=nacosAddressServer,proto3" json:"nacosAddressServer,omitempty"`
	NacosAccessKey        string   `protobuf:"bytes,6,opt,name=nacosAccessKey,proto3" json:"nacosAccessKey,omitempty"`
	NacosSecretKey        string   `protobuf:"bytes,7,opt,name=nacosSecretKey,proto3" json:"nacosSecretKey,omitempty"`
	NacosNamespaceId      string   `protobuf:"bytes,8,opt,name=nacosNamespaceId,proto3" json:"nacosNamespaceId,omitempty"`
	NacosNamespace        string   `protobuf:"bytes,9,opt,name=nacosNamespace,proto3" json:"nacosNamespace,omitempty"`
	NacosGroups           []string `protobuf:"bytes,10,rep,name=nacosGroups,proto3" json:"nacosGroups,omitempty"`
	NacosRefreshInterval  int64    `protobuf:"varint,11,opt,name=nacosRefreshInterval,proto3" json:"nacosRefreshInterval,omitempty"`
	ConsulNamespace       string   `protobuf:"bytes,12,opt,name=consulNamespace,proto3" json:"consulNamespace,omitempty"`
	ZkServicesPath        []string `protobuf:"bytes,13,rep,name=zkServicesPath,proto3" json:"zkServicesPath,omitempty"`
	ConsulDatacenter      string   `protobuf:"bytes,14,opt,name=consulDatacenter,proto3" json:"consulDatacenter,omitempty"`
	ConsulAuthToken       string   `protobuf:"bytes,15,opt,name=consulAuthToken,proto3" json:"consulAuthToken,omitempty"`
	ConsulServiceTag      string   `protobuf:"bytes,16,opt,name=consulServiceTag,proto3" json:"consulServiceTag,omitempty"`
	ConsulRefreshInterval int64    `protobuf:"varint,17,opt,name=consulRefreshInterval,proto3" json:"consulRefreshInterval,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *RegistryConfig) Reset()         { *m = RegistryConfig{} }
func (m *RegistryConfig) String() string { return proto.CompactTextString(m) }
func (*RegistryConfig) ProtoMessage()    {}
func (*RegistryConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3fcc59a15c34642d, []int{1}
}
func (m *RegistryConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegistryConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegistryConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegistryConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistryConfig.Merge(m, src)
}
func (m *RegistryConfig) XXX_Size() int {
	return m.Size()
}
func (m *RegistryConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistryConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RegistryConfig proto.InternalMessageInfo

func (m *RegistryConfig) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RegistryConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegistryConfig) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *RegistryConfig) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *RegistryConfig) GetNacosAddressServer() string {
	if m != nil {
		return m.NacosAddressServer
	}
	return ""
}

func (m *RegistryConfig) GetNacosAccessKey() string {
	if m != nil {
		return m.NacosAccessKey
	}
	return ""
}

func (m *RegistryConfig) GetNacosSecretKey() string {
	if m != nil {
		return m.NacosSecretKey
	}
	return ""
}

func (m *RegistryConfig) GetNacosNamespaceId() string {
	if m != nil {
		return m.NacosNamespaceId
	}
	return ""
}

func (m *RegistryConfig) GetNacosNamespace() string {
	if m != nil {
		return m.NacosNamespace
	}
	return ""
}

func (m *RegistryConfig) GetNacosGroups() []string {
	if m != nil {
		return m.NacosGroups
	}
	return nil
}

func (m *RegistryConfig) GetNacosRefreshInterval() int64 {
	if m != nil {
		return m.NacosRefreshInterval
	}
	return 0
}

func (m *RegistryConfig) GetConsulNamespace() string {
	if m != nil {
		return m.ConsulNamespace
	}
	return ""
}

func (m *RegistryConfig) GetZkServicesPath() []string {
	if m != nil {
		return m.ZkServicesPath
	}
	return nil
}

func (m *RegistryConfig) GetConsulDatacenter() string {
	if m != nil {
		return m.ConsulDatacenter
	}
	return ""
}

func (m *RegistryConfig) GetConsulAuthToken() string {
	if m != nil {
		return m.ConsulAuthToken
	}
	return ""
}

func (m *RegistryConfig) GetConsulServiceTag() string {
	if m != nil {
		return m.ConsulServiceTag
	}
	return ""
}

func (m *RegistryConfig) GetConsulRefreshInterval() int64 {
	if m != nil {
		return m.ConsulRefreshInterval
	}
	return 0
}

func init() {
	proto.RegisterType((*McpBridge)(nil), "higress.networking.v1.McpBridge")
	proto.RegisterType((*RegistryConfig)(nil), "higress.networking.v1.RegistryConfig")
}

func init() { proto.RegisterFile("networking/v1/mcp_bridge.proto", fileDescriptor_3fcc59a15c34642d) }

var fileDescriptor_3fcc59a15c34642d = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x86, 0xc9, 0xb6, 0x5b, 0xed, 0xd4, 0xed, 0xae, 0x83, 0x0b, 0x83, 0x48, 0x0d, 0x0b, 0x4a,
	0x10, 0x49, 0xd8, 0xd5, 0x2b, 0xef, 0x5a, 0x15, 0x59, 0x44, 0x91, 0xec, 0x5e, 0x79, 0xb3, 0x4c,
	0x26, 0xa7, 0xc9, 0xd0, 0x24, 0x13, 0x66, 0xa6, 0x91, 0xfa, 0x48, 0x3e, 0x89, 0x97, 0x3e, 0x82,
	0xf4, 0x49, 0x64, 0x26, 0x35, 0x49, 0xb3, 0xbd, 0x6b, 0xbf, 0xf3, 0x9f, 0xff, 0x3f, 0x73, 0xc8,
	0x41, 0xb3, 0x02, 0xf4, 0x0f, 0x21, 0x57, 0xbc, 0x48, 0x82, 0xea, 0x32, 0xc8, 0x59, 0x79, 0x17,
	0x49, 0x1e, 0x27, 0xe0, 0x97, 0x52, 0x68, 0x81, 0xcf, 0x53, 0x9e, 0x48, 0x50, 0xca, 0x6f, 0x75,
	0x7e, 0x75, 0xf9, 0xf4, 0x79, 0x22, 0x44, 0x92, 0x41, 0x40, 0x4b, 0x1e, 0x2c, 0x39, 0x64, 0xf1,
	0x5d, 0x04, 0x29, 0xad, 0xb8, 0x90, 0x75, 0xdf, 0x45, 0x88, 0xc6, 0x5f, 0x58, 0xb9, 0xb0, 0x56,
	0xf8, 0x23, 0x42, 0x12, 0x12, 0xae, 0xb4, 0xe4, 0xa0, 0x88, 0xe3, 0x0e, 0xbc, 0xc9, 0xd5, 0x0b,
	0xff, 0xa0, 0xb3, 0x1f, 0xd6, 0xc2, 0xcd, 0x7b, 0x51, 0x2c, 0x79, 0x12, 0x76, 0x1a, 0x2f, 0x7e,
	0x1d, 0xa3, 0xe9, 0x7e, 0x19, 0x13, 0x34, 0xd4, 0x9b, 0x12, 0x88, 0xe3, 0x3a, 0xde, 0x78, 0x31,
	0xdc, 0xce, 0x9d, 0xa3, 0xd0, 0x12, 0x8c, 0xd1, 0xb0, 0xa0, 0x39, 0x90, 0x23, 0x53, 0x09, 0xed,
	0x6f, 0xfc, 0x0c, 0x8d, 0x62, 0x91, 0x53, 0x5e, 0x90, 0x41, 0x47, 0xbf, 0x63, 0xc6, 0xab, 0x14,
	0x52, 0x93, 0xa1, 0xeb, 0x78, 0x27, 0xff, 0xbd, 0x0c, 0xc1, 0x3e, 0xc2, 0x05, 0x65, 0x42, 0xcd,
	0xe3, 0xd8, 0x4c, 0x7c, 0x03, 0xb2, 0x02, 0x49, 0x8e, 0xad, 0xf3, 0x81, 0x0a, 0x7e, 0x89, 0xa6,
	0x35, 0x65, 0x0c, 0x94, 0xfa, 0x0c, 0x1b, 0x32, 0xb2, 0xda, 0x1e, 0x6d, 0x74, 0x37, 0xc0, 0x24,
	0x68, 0xa3, 0x7b, 0xd0, 0xd1, 0x35, 0x14, 0xbf, 0x42, 0x67, 0x96, 0x7c, 0xa5, 0x39, 0xa8, 0x92,
	0x32, 0xb8, 0x8e, 0xc9, 0x43, 0xab, 0xbc, 0xc7, 0x1b, 0xcf, 0x86, 0x91, 0x71, 0xc7, 0xb3, 0xa1,
	0xd8, 0x45, 0x13, 0x4b, 0x3e, 0x49, 0xb1, 0x2e, 0x15, 0x41, 0xee, 0xc0, 0x1b, 0x87, 0x5d, 0x84,
	0xaf, 0xd0, 0x13, 0xfb, 0x37, 0x84, 0xa5, 0x04, 0x95, 0x5e, 0x17, 0x1a, 0x64, 0x45, 0x33, 0x32,
	0x71, 0x1d, 0x6f, 0x10, 0x1e, 0xac, 0x61, 0x0f, 0x9d, 0x32, 0x51, 0xa8, 0x75, 0xd6, 0xc6, 0x3f,
	0xb2, 0xf1, 0x7d, 0x6c, 0xe6, 0xfc, 0xb9, 0x32, 0xfb, 0xe2, 0x0c, 0xd4, 0x37, 0xaa, 0x53, 0x72,
	0x62, 0x47, 0xe8, 0x51, 0xf3, 0xf6, 0xba, 0xf5, 0x03, 0xd5, 0x94, 0x81, 0x09, 0x22, 0xd3, 0xfa,
	0xed, 0x7d, 0xde, 0xa6, 0xcf, 0xd7, 0x3a, 0xbd, 0x15, 0x2b, 0x28, 0xc8, 0x69, 0x37, 0xbd, 0xc1,
	0xad, 0xeb, 0x2e, 0xeb, 0x96, 0x26, 0xe4, 0xac, 0xeb, 0xda, 0x72, 0xfc, 0x16, 0x9d, 0xd7, 0xac,
	0xbf, 0x88, 0xc7, 0x76, 0x11, 0x87, 0x8b, 0x8b, 0x77, 0xbf, 0xb7, 0x33, 0xe7, 0xcf, 0x76, 0xe6,
	0xfc, 0xdd, 0xce, 0x9c, 0xef, 0xaf, 0x13, 0xae, 0xd3, 0x75, 0xe4, 0x33, 0x91, 0x07, 0x34, 0xe3,
	0x11, 0x8d, 0x68, 0xb0, 0xfb, 0xfe, 0xed, 0x0d, 0xed, 0x5d, 0x61, 0x34, 0xb2, 0x37, 0xf4, 0xe6,
	0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa3, 0xc9, 0xb4, 0x8b, 0x9d, 0x03, 0x00, 0x00,
}

func (m *McpBridge) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *McpBridge) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *McpBridge) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Registries) > 0 {
		for iNdEx := len(m.Registries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Registries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMcpBridge(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *RegistryConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegistryConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RegistryConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.ConsulRefreshInterval != 0 {
		i = encodeVarintMcpBridge(dAtA, i, uint64(m.ConsulRefreshInterval))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if len(m.ConsulServiceTag) > 0 {
		i -= len(m.ConsulServiceTag)
		copy(dAtA[i:], m.ConsulServiceTag)
		i = encodeVarintMcpBridge(dAtA, i, uint64(len(m.ConsulServiceTag)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if len(m.ConsulAuthToken) > 0 {
		i -= len(m.ConsulAuthToken)
		copy(dAtA[i:], m.ConsulAuthToken)
		i = encodeVarintMcpBridge(dAtA, i, uint64(len(m.ConsulAuthToken)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.ConsulDatacenter) > 0 {
		i -= len(m.ConsulDatacenter)
		copy(dAtA[i:], m.ConsulDatacenter)
		i = encodeVarintMcpBridge(dAtA, i, uint64(len(m.ConsulDatacenter)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.ZkServicesPath) > 0 {
		for iNdEx := len(m.ZkServicesPath) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ZkServicesPath[iNdEx])
			copy(dAtA[i:], m.ZkServicesPath[iNdEx])
			i = encodeVarintMcpBridge(dAtA, i, uint64(len(m.ZkServicesPath[iNdEx])))
			i--
			dAtA[i] = 0x6a
		}
	}
	if len(m.ConsulNamespace) > 0 {
		i -= len(m.ConsulNamespace)
		copy(dAtA[i:], m.ConsulNamespace)
		i = encodeVarintMcpBridge(dAtA, i, uint64(len(m.ConsulNamespace)))
		i--
		dAtA[i] = 0x62
	}
	if m.NacosRefreshInterval != 0 {
		i = encodeVarintMcpBridge(dAtA, i, uint64(m.NacosRefreshInterval))
		i--
		dAtA[i] = 0x58
	}
	if len(m.NacosGroups) > 0 {
		for iNdEx := len(m.NacosGroups) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.NacosGroups[iNdEx])
			copy(dAtA[i:], m.NacosGroups[iNdEx])
			i = encodeVarintMcpBridge(dAtA, i, uint64(len(m.NacosGroups[iNdEx])))
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.NacosNamespace) > 0 {
		i -= len(m.NacosNamespace)
		copy(dAtA[i:], m.NacosNamespace)
		i = encodeVarintMcpBridge(dAtA, i, uint64(len(m.NacosNamespace)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.NacosNamespaceId) > 0 {
		i -= len(m.NacosNamespaceId)
		copy(dAtA[i:], m.NacosNamespaceId)
		i = encodeVarintMcpBridge(dAtA, i, uint64(len(m.NacosNamespaceId)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.NacosSecretKey) > 0 {
		i -= len(m.NacosSecretKey)
		copy(dAtA[i:], m.NacosSecretKey)
		i = encodeVarintMcpBridge(dAtA, i, uint64(len(m.NacosSecretKey)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.NacosAccessKey) > 0 {
		i -= len(m.NacosAccessKey)
		copy(dAtA[i:], m.NacosAccessKey)
		i = encodeVarintMcpBridge(dAtA, i, uint64(len(m.NacosAccessKey)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.NacosAddressServer) > 0 {
		i -= len(m.NacosAddressServer)
		copy(dAtA[i:], m.NacosAddressServer)
		i = encodeVarintMcpBridge(dAtA, i, uint64(len(m.NacosAddressServer)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Port != 0 {
		i = encodeVarintMcpBridge(dAtA, i, uint64(m.Port))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Domain) > 0 {
		i -= len(m.Domain)
		copy(dAtA[i:], m.Domain)
		i = encodeVarintMcpBridge(dAtA, i, uint64(len(m.Domain)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintMcpBridge(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Type) > 0 {
		i -= len(m.Type)
		copy(dAtA[i:], m.Type)
		i = encodeVarintMcpBridge(dAtA, i, uint64(len(m.Type)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMcpBridge(dAtA []byte, offset int, v uint64) int {
	offset -= sovMcpBridge(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *McpBridge) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Registries) > 0 {
		for _, e := range m.Registries {
			l = e.Size()
			n += 1 + l + sovMcpBridge(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *RegistryConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovMcpBridge(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovMcpBridge(uint64(l))
	}
	l = len(m.Domain)
	if l > 0 {
		n += 1 + l + sovMcpBridge(uint64(l))
	}
	if m.Port != 0 {
		n += 1 + sovMcpBridge(uint64(m.Port))
	}
	l = len(m.NacosAddressServer)
	if l > 0 {
		n += 1 + l + sovMcpBridge(uint64(l))
	}
	l = len(m.NacosAccessKey)
	if l > 0 {
		n += 1 + l + sovMcpBridge(uint64(l))
	}
	l = len(m.NacosSecretKey)
	if l > 0 {
		n += 1 + l + sovMcpBridge(uint64(l))
	}
	l = len(m.NacosNamespaceId)
	if l > 0 {
		n += 1 + l + sovMcpBridge(uint64(l))
	}
	l = len(m.NacosNamespace)
	if l > 0 {
		n += 1 + l + sovMcpBridge(uint64(l))
	}
	if len(m.NacosGroups) > 0 {
		for _, s := range m.NacosGroups {
			l = len(s)
			n += 1 + l + sovMcpBridge(uint64(l))
		}
	}
	if m.NacosRefreshInterval != 0 {
		n += 1 + sovMcpBridge(uint64(m.NacosRefreshInterval))
	}
	l = len(m.ConsulNamespace)
	if l > 0 {
		n += 1 + l + sovMcpBridge(uint64(l))
	}
	if len(m.ZkServicesPath) > 0 {
		for _, s := range m.ZkServicesPath {
			l = len(s)
			n += 1 + l + sovMcpBridge(uint64(l))
		}
	}
	l = len(m.ConsulDatacenter)
	if l > 0 {
		n += 1 + l + sovMcpBridge(uint64(l))
	}
	l = len(m.ConsulAuthToken)
	if l > 0 {
		n += 1 + l + sovMcpBridge(uint64(l))
	}
	l = len(m.ConsulServiceTag)
	if l > 0 {
		n += 2 + l + sovMcpBridge(uint64(l))
	}
	if m.ConsulRefreshInterval != 0 {
		n += 2 + sovMcpBridge(uint64(m.ConsulRefreshInterval))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovMcpBridge(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMcpBridge(x uint64) (n int) {
	return sovMcpBridge(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *McpBridge) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMcpBridge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: McpBridge: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: McpBridge: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Registries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcpBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMcpBridge
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMcpBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Registries = append(m.Registries, &RegistryConfig{})
			if err := m.Registries[len(m.Registries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMcpBridge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMcpBridge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RegistryConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMcpBridge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegistryConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegistryConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcpBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcpBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcpBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcpBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcpBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcpBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcpBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcpBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcpBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Domain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Port", wireType)
			}
			m.Port = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcpBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Port |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NacosAddressServer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcpBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcpBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcpBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NacosAddressServer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NacosAccessKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcpBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcpBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcpBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NacosAccessKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NacosSecretKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcpBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcpBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcpBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NacosSecretKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NacosNamespaceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcpBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcpBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcpBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NacosNamespaceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NacosNamespace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcpBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcpBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcpBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NacosNamespace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NacosGroups", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcpBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcpBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcpBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NacosGroups = append(m.NacosGroups, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NacosRefreshInterval", wireType)
			}
			m.NacosRefreshInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcpBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NacosRefreshInterval |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsulNamespace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcpBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcpBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcpBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsulNamespace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZkServicesPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcpBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcpBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcpBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ZkServicesPath = append(m.ZkServicesPath, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsulDatacenter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcpBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcpBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcpBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsulDatacenter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsulAuthToken", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcpBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcpBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcpBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsulAuthToken = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsulServiceTag", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcpBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcpBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcpBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsulServiceTag = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsulRefreshInterval", wireType)
			}
			m.ConsulRefreshInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcpBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConsulRefreshInterval |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMcpBridge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMcpBridge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMcpBridge(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMcpBridge
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMcpBridge
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMcpBridge
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMcpBridge
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMcpBridge
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMcpBridge
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMcpBridge        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMcpBridge          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMcpBridge = fmt.Errorf("proto: unexpected end of group")
)
